# Generated by Django 2.2.5 on 2020-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('food_needs', models.TextField(blank=True)),
                ('user_type', models.BooleanField()),
                ('has_vietnamese_background', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
