# Generated by Django 2.2.5 on 2020-02-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_type',
            new_name='is_student',
        ),
    ]
