# Generated by Django 2.2.10 on 2020-12-29 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image_link', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField(verbose_name='startTime')),
                ('endTime', models.DateTimeField(verbose_name='endTime')),
                ('location', models.CharField(max_length=200)),
                ('max_people', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('registrations', models.ManyToManyField(blank=True, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
