# Generated by Django 2.2.10 on 2020-12-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=200)),
                ('event_image_link', models.CharField(max_length=200)),
                ('event_startTime', models.CharField(max_length=200)),
                ('event_endTime', models.CharField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
                ('event_open_for', models.CharField(max_length=200)),
                ('event_max_people', models.CharField(max_length=200)),
                ('event_people_joined', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
