# Generated by Django 2.2.10 on 2020-12-30 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='waiting_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
