# Generated by Django 2.2.10 on 2020-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_waiting_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_people',
            field=models.IntegerField(max_length=200),
        ),
    ]
