# Generated by Django 2.2.10 on 2020-12-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201228_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_people_joined',
        ),
    ]
