# Generated by Django 2.2.10 on 2020-12-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_event_people_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_endTime',
            field=models.DateTimeField(verbose_name='endTime'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_startTime',
            field=models.DateTimeField(verbose_name='startTime'),
        ),
    ]
