# Generated by Django 2.2.10 on 2021-01-01 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft_publish_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='draft_publish_time'),
        ),
    ]
