# Generated by Django 2.2.10 on 2020-12-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201228_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_open_for',
        ),
    ]
