# Generated by Django 2.2.10 on 2020-12-28 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_event_open_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(blank=True, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
