# Generated by Django 2.2.10 on 2021-01-01 21:18

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_draft_publish_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='event',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date last edited'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
