# Generated by Django 2.2.10 on 2021-01-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210101_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_event_image.jpg', upload_to='event_uploads'),
        ),
    ]
