# Generated by Django 2.2.10 on 2021-01-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_link',
        ),
    ]
