# Generated by Django 2.2.10 on 2021-01-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('medlem1', 'medlem2'), ('alle1', 'alle2')], default='medlem', max_length=50),
        ),
    ]
