# Generated by Django 2.2.10 on 2021-01-04 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellationDeadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cancellation deadline'),
        ),
        migrations.AddField(
            model_name='event',
            name='registrationDeadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration deadline'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('medlem', 'Membership required'), ('alle', 'Open for all')], default='medlem', max_length=50),
        ),
    ]
