# Generated by Django 2.2.10 on 2021-01-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210104_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='date last edited'),
        ),
    ]
