# Generated by Django 2.2.10 on 2021-01-05 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_auto_20210104_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance',
            field=models.ManyToManyField(blank=True, related_name='attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='secret_url',
            field=models.CharField(default='d36e07575d3e462b918ddc6d782a8d85', max_length=100),
        ),
    ]
