# Generated by Django 2.2.10 on 2021-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20210105_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='secret_url',
            field=models.CharField(default='4c7800d6e9114f3f84dfd4fcafc2bbdb', max_length=100),
        ),
    ]
