# Generated by Django 2.2.10 on 2021-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20210108_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='secret_url',
            field=models.CharField(default='6894ce80e26746068b55c363166e49b1', max_length=100),
        ),
    ]
