# Generated by Django 2.2.10 on 2021-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210108_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='secret_url',
            field=models.CharField(default='12cbc69a136949f9af98a48fc7412ae0', max_length=100),
        ),
    ]
