# Generated by Django 2.2.10 on 2021-01-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsaituser',
            name='food_needs',
            field=models.CharField(blank=True, max_length=240, verbose_name='food_needs'),
        ),
    ]
