# Generated by Django 2.2.10 on 2021-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vsaituser_food_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2021', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='vsaituser',
            name='memberships',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='home.Membership'),
        ),
    ]
