# Generated by Django 2.2.10 on 2021-01-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210105_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsaituser',
            name='membership',
        ),
    ]
