# Generated by Django 2.2.10 on 2021-01-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_vsaituser_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsaituser',
            name='pending_membership',
            field=models.BooleanField(default=False),
        ),
    ]
