# Generated by Django 2.2.10 on 2021-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vsaituser_pending_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsaituser',
            name='anonymous_display',
            field=models.BooleanField(default=True),
        ),
    ]
