# Generated by Django 2.2.10 on 2021-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_vsaituser_anonymous_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsaituser',
            name='alert_membership_read',
            field=models.BooleanField(default=False),
        ),
    ]
