# Generated by Django 2.2.10 on 2020-10-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201022_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='has_membership',
            new_name='membership',
        ),
    ]
